Importing the dependencies

In [158]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score  
from sklearn.preprocessing import StandardScaler

Importing the datasets

In [159]:
train_data = pd.read_csv('Datasets/train.csv')
test_data = pd.read_csv('Datasets/test.csv')

In [160]:
train_data.head()

,id,annual_income,debt_to_income_ratio,credit_score,loan_amount,interest_rate,gender,marital_status,education_level,employment_status,loan_purpose,grade_subgrade,loan_paid_back
0,0,29367.99,0.084,736,2528.42,13.67,Female,Single,High School,Self-employed,Other,C3,1.0
1,1,22108.02,0.166,636,4593.10,12.92,Male,Married,Master's,Employed,Debt consolidation,D3,0.0
2,2,49566.20,0.097,694,17005.15,9.76,Male,Single,High School,Employed,Debt consolidation,C5,1.0
3,3,46858.25,0.065,533,4682.48,16.10,Female,Single,High School,Employed,Debt consolidation,F1,1.0
4,4,25496.70,0.053,665,12184.43,10.21,Male,Married,High School,Employed,Other,D1,1.0

In [161]:
test_data.head()

,id,annual_income,debt_to_income_ratio,credit_score,loan_amount,interest_rate,gender,marital_status,education_level,employment_status,loan_purpose,grade_subgrade
0,593994,28781.05,0.049,626,11461.42,14.73,Female,Single,High School,Employed,Other,D5
1,593995,46626.39,0.093,732,15492.25,12.85,Female,Married,Master's,Employed,Other,C1
2,593996,54954.89,0.367,611,3796.41,13.29,Male,Single,Bachelor's,Employed,Debt consolidation,D1
3,593997,25644.63,0.110,671,6574.30,9.57,Female,Single,Bachelor's,Employed,Debt consolidation,C3
4,593998,25169.64,0.081,688,17696.89,12.80,Female,Married,PhD,Employed,Business,C1

In [162]:
train_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 593994 entries, 0 to 593993
Data columns (total 13 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   id                    593994 non-null  int64
 1   annual_income         593994 non-null  float64
 2   debt_to_income_ratio  593994 non-null  float64
 3   credit_score          593994 non-null  int64
 4   loan_amount           593994 non-null  float64
 5   interest_rate         593994 non-null  float64
 6   gender                593994 non-null  object
 7   marital_status        593994 non-null  object
 8   education_level       593994 non-null  object
 9   employment_status     593994 non-null  object
 10  loan_purpose          593994 non-null  object
 11  grade_subgrade        593994 non-null  object
 12  loan_paid_back        593994 non-null  float64
dtypes: float64(5), int64(2), object(6)
memory usage: 58.9+ MB

In [163]:
train_data.isnull().sum()

id                      0
annual_income           0
debt_to_income_ratio    0
credit_score            0
loan_amount             0
interest_rate           0
gender                  0
marital_status          0
education_level         0
employment_status       0
loan_purpose            0
grade_subgrade          0
loan_paid_back          0
dtype: int64

Encoding the data

In [164]:
encoder = LabelEncoder()

for i in train_data.columns:
    if train_data[i].dtypes == "object":    
        train_data[i] = encoder.fit_transform(train_data[i].astype(str))
        test_data[i] = encoder.fit_transform(test_data[i].astype(str))

In [165]:
train_data.head()

,id,annual_income,debt_to_income_ratio,credit_score,loan_amount,interest_rate,gender,marital_status,education_level,employment_status,loan_purpose,grade_subgrade,loan_paid_back
0,0,29367.99,0.084,736,2528.42,13.67,0,2,1,2,6,12,1.0
1,1,22108.02,0.166,636,4593.10,12.92,1,1,2,0,2,17,0.0
2,2,49566.20,0.097,694,17005.15,9.76,1,2,1,0,2,14,1.0
3,3,46858.25,0.065,533,4682.48,16.10,0,2,1,0,2,25,1.0
4,4,25496.70,0.053,665,12184.43,10.21,1,1,1,0,6,15,1.0

In [166]:
train_data['loan_paid_back'] = train_data['loan_paid_back'].astype(int)

In [167]:
train_data['loan_paid_back']

0         1
1         0
2         1
3         1
4         1
         ..
593989    1
593990    1
593991    1
593992    1
593993    1
Name: loan_paid_back, Length: 593994, dtype: int64

In [168]:
train_data.drop(columns=['id'],inplace=True)
test_data.drop(columns=['id'],inplace=True)

In [169]:
scaler = StandardScaler()

In [170]:
for i in train_data.columns:
    if i != 'loan_paid_back':
        train_data[i] = scaler.fit_transform(train_data[[i]])    

for i in test_data.columns:
    test_data[i] = scaler.fit_transform(test_data[[i]])

In [171]:
test_data

,annual_income,debt_to_income_ratio,credit_score,loan_amount,interest_rate,gender,marital_status,education_level,employment_status,loan_purpose,grade_subgrade
0,-0.728006,-1.043756,-0.989459,-0.513617,1.178469,-0.955777,0.902599,0.173697,-0.513957,2.040421,0.982508
1,-0.060132,-0.402190,0.916193,0.068692,0.246668,-0.955777,-0.805971,1.201377,-0.513957,2.040421,-0.772640
2,0.251568,3.593019,-1.259127,-1.620933,0.464749,0.994910,0.902599,-0.853982,-0.513957,-0.370222,0.202442
3,-0.845389,-0.154312,-0.180456,-1.219629,-1.379028,-0.955777,0.902599,-0.853982,-0.513957,-0.370222,-0.382607
4,-0.863165,-0.577162,0.125167,0.387183,0.221886,-0.955777,-0.805971,3.256735,-0.513957,-1.575544,-0.772640
...,...,...,...,...,...,...,...,...,...,...,...
254564,1.669294,-0.766716,1.131927,2.121775,0.558920,-0.955777,0.902599,-0.853982,-0.513957,-0.370222,-1.552706
254565,0.022957,-0.431352,-0.845636,0.760974,-1.374071,-0.955777,-0.805971,0.173697,-0.513957,-0.370222,0.787491
254566,-1.031623,-0.358447,0.664503,1.642668,-1.661542,0.994910,0.902599,1.201377,-0.513957,-0.370222,-0.187591
254567,-0.528750,-0.387609,1.042038,-0.564766,-1.260074,0.994910,0.902599,-0.853982,-0.513957,-1.575544,-0.577624
254568,-0.097515,-0.037663,-1.025415,0.610993,-0.353055,-0.955777,-0.805971,0.173697,-0.513957,-0.972883,0.592475

Splitting the data

In [172]:
X = train_data.drop(columns=['loan_paid_back'])
Y = train_data['loan_paid_back']

Train Test Split

In [173]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=42)

Model Implementation

In [174]:
model = LogisticRegression()

model.fit(X_train, Y_train)

LogisticRegression()

In [175]:
model.predict(X_test)

array([1, 1, 1, ..., 1, 1, 1], shape=(118799,))

Getting the prediction for the test dataset

In [176]:
test_predictions = model.predict(test_data)

Submitting the sample submission

In [177]:
sample = pd.read_csv('Datasets/sample_submission.csv')

In [178]:
Final_prediction = pd.DataFrame({
    'id': sample['id'][:len(test_predictions)],  
    'Price': test_predictions
})

Converting into the submission file

In [179]:
Final_prediction.to_csv("Datasets/Final_Submission.csv", index=False)